updating queries and tests to now only filter for approved profiles
mozilla/network-pulse-api pull request #797
Opened 2022-05-19 21:46 UTC by danielfmiranda

2022-05-24 20:08 UTC, tbrlpld requested changes
Thanks for this @danielfmiranda 

I have added a few smaller comments regarding the specific implementation. 

I do, however, have some more big picture questions around this one:

1. You description mentions that the user should be able to CRUD (create/read/update/delete) their own posts, even when they are "inactive". It would be good to add tests around this behaviour. I don't see these tests as part of this PR. Maybe I missed something. 
2. Why are we using the `EmailUser.is_active` flag instead of the [`UserProfile.is_active`](https://github.com/mozilla/network-pulse-api/blob/5d739ba5033094a6efcbafd18cc2aafe01567d18/pulseapi/profiles/models/profiles.py#L52) flag? From the comment on the `UserProfile.is_active` it sounds very much like that would be the intended use of that flag. The `User.is_active` flag seems like it might mess with the authentication ability for the user (see [this section in the docs](https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.is_active)). If I understand the context for the ticket correct, we want to users to be able to create content and see it themselves. But, we don't want that content to be shown to other "users" until a moderator has "approved" the user. It seems like we should set  `User.is_active` automatically to `True` on sign up to allow the user to authenticate, but use `UserProfile.is_active` filtering mechanism which will be set `True` manually by a moderator. 
 
Please let me know if I am missing something here.

2022-06-01 00:07 UTC, danielfmiranda commented on pulseapi/entries/models.py
> +        return self.filter(published_by__profile__related_user__is_active=True)
Great catch Tibor!

2022-06-02 18:07 UTC, danielfmiranda commented on pulseapi/creators/tests.py
>      def test_creator_filtering(self):
Good idea! I have added a test for that

2022-06-03 05:48 UTC, danielfmiranda commented
Closing this pr until the work in #798 is complete.

2022-06-10 00:11 UTC, danielfmiranda commented
Reopening as the pr #798 is approved! However, before merging that one in, I would like to get this approved too so we can make sure that possible spam posts are not displayed on pulse

2022-06-10 17:28 UTC, tbrlpld requested changes

2022-06-10 17:28 UTC, tbrlpld commented on pulseapi/creators/tests.py
> +        BasicEmailUserFactory(profile=profile, is_active=False)
**Issue** The user should be active, but the profile should be inactive. That is the change in the logic we wanted. 

I guess the docs string and method name should also be updated accordingly.

2022-06-10 17:28 UTC, tbrlpld commented on pulseapi/entries/models.py
> +        return self.filter(published_by__is_active=True)
**Issue** `published_by` points to the email user. We want to only show entries by user's with active profiles. The user accounts should all be active.

2022-06-10 17:29 UTC, tbrlpld commented
@danielfmiranda I think we need to update the logic here still do exclude based on the profiles active state, not the users.

2022-06-12 20:02 UTC, closed without merging